# --- Stripe wiring ---
stripe:
  api-key: ${API_KEY}
  webhook-secret: ${WEBHOOK_SECRET}
  payment-confirmation.url: ${PAYMENT_CONFIRMATION_URL}

spring:
  application.name: payment-service
  # --- Postgres wiring ---
  datasource:
    url: jdbc:postgresql://payment-db-service:5432/payment-db
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  # --- JPA wiring ---
  jpa:
    hibernate:
      ddl-auto: validate                        # schema managed by Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- Liquibase wiring ---
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public

  # --- Kafka wiring ---
  kafka:
    bootstrap-servers: kafka:9092      # change to kafka:9092 in Docker/K8s
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      # allow any package for JsonDeserializer
      spring.json.trusted.packages: '*'