server.port: 8081
spring:
  application.name: order-service

  # --- Postgres wiring ---
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  # --- JPA ---
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- Liquibase wiring ---
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public

  # --- Quartz wiring ---
  quartz:
    # Persist jobs & triggers in the database
    job-store-type: jdbc
    jdbc:
      # to not run the bundled DDL script every time
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

  # --- Kafka wiring ---
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      # allow any package for JsonDeserializer
      spring.json.trusted.packages: '*'